### ISSUE TITLE
Module build failed: Error: dyld: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib

### ISSUE THREAD

**Issue by mrdulin** [tcoopman/image-webpack-loader#60] opened 2016-12-21 07:23 UTC
full error: 
```bash
ERROR in ./src/images/bg.jpg
Module build failed: Error: dyld: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
  Referenced from: /Users/dulin/workspace/webpack-summer/node_modules/mozjpeg/vendor/cjpeg
  Reason: image not found

    at Promise.all.then.arr (/Users/dulin/workspace/webpack-summer/node_modules/execa/index.js:170:11)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 @ ../~/css-loader!./src/style.css 6:100-126
```

it seems not support `jpg` image?

**Comment by tcoopman** [comment] 2016-12-27 08:16
Can you post your webpack config?
And what version are you using?

**Comment by tcoopman** [comment] 2016-12-27 08:23
Duplicate of #51

**Closed by tcoopman** 2016-12-27 08:23 UTC
Labels: duplicate

**Comment by mrdulin** [comment] 2016-12-27 12:54
@tcoopman 

```js
const htmlWebpackPlugin = require('html-webpack-plugin');
var CleanWebpackPlugin = require('clean-webpack-plugin');
var path = require('path');

module.exports = {
    entry: './src',
    output: {
        path: 'dist',
        filename: 'bundle.[hash].js'
    },
    module: {
        loaders: [{
            test: /.*\.(gif|png|jpe?g|svg)$/i,
            exclude: /node_modules/,
            loaders: [
                'file?hash=sha512&digest=hex&name=images/[name].[hash:8].[ext]',
                'image-webpack'
            ]
        }, {
            test: /\.css$/,
            exclude: /node_modules/,
            loader: 'style!css'
        }]
    },
    imageWebpackLoader: {
        mozjpeg: {
            quality: 65
        },
        pngquant: {
            quality: "65-90",
            speed: 4
        }
    },
    plugins: [
        new CleanWebpackPlugin('dist', {
            root: __dirname,
            verbose: true,
            dry: false
        }),
        new htmlWebpackPlugin({
            template: './src/index.html'
        })
    ]
}

```

**Comment by tcoopman** [comment] 2016-12-27 14:11
@mrdulin. Thanks, it's a duplicate bug of #51 
Maybe you can check over there how you can fix it.

**Comment by jose920405** [comment] 2017-09-18 20:31
Just need update it with `brew`.

`brew reinstall libpng`

**Comment by SebastianoF** [comment] 2018-08-09 09:04
To solve the problem I applied the following workaround (that is not optimal, but it is doing the job).

1) locate libpng16.16.dylib in the system with
```
find /opt -name "libpng16.16.dylib"
```
that turned out to be under `/opt/X11/lib/` in my system.

2) make a symlink of "libpng16.16.dylib" where required:
```
sudo ln -s /opt/X11/lib/libpng16.16.dylib /usr/local/opt/libpng/lib/libpng16.16.dylib
```

Note that before step 2, you may need to create the folders `/usr/local/opt/libpng/lib/` if not present, with:
```
sudo mkdir -p /usr/local/opt/libpng/lib/
```
